--------------------------------------------------------
--  파일이 생성됨 - 목요일-9월-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPBOARDATTACH
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TIPBOARDATTACH" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"UPLOADPATH" VARCHAR2(200 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILETYPE" CHAR(1 BYTE), 
	"BNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."TIPBOARDATTACH"."UUID" IS 'UUID';
   COMMENT ON COLUMN "ADMIN"."TIPBOARDATTACH"."UPLOADPATH" IS '업로드경로';
   COMMENT ON COLUMN "ADMIN"."TIPBOARDATTACH"."FILENAME" IS '파일이름';
REM INSERTING into ADMIN.TIPBOARDATTACH
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TIPLISTATTACH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TIPLISTATTACH_PK" ON "ADMIN"."TIPBOARDATTACH" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPBOARDATTACH
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TIPBOARDATTACH" ADD CONSTRAINT "TIPLISTATTACH_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TIPBOARDATTACH" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TIPBOARDATTACH" MODIFY ("FILENAME" NOT NULL ENABLE);
