--------------------------------------------------------
--  ÆÄÀÏÀÌ »ý¼ºµÊ - ¿ù¿äÀÏ-9¿ù-30-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPBOARDCOMMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TIPBOARDCOMMENT" 
   (	"RE_NUM" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"CONTENT" CLOB, 
	"RE_DATE" DATE, 
	"NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ADMIN"."TIPBOARDCOMMENT"."RE_NUM" IS '´ñ±Û¹øÈ£';
   COMMENT ON COLUMN "ADMIN"."TIPBOARDCOMMENT"."NAME" IS '´ñ±ÛÀÛ¼ºÀÚ';
   COMMENT ON COLUMN "ADMIN"."TIPBOARDCOMMENT"."CONTENT" IS '´ñ±Û³»¿ë';
   COMMENT ON COLUMN "ADMIN"."TIPBOARDCOMMENT"."RE_DATE" IS '´ñ±ÛÀÛ¼ºÀÏ';
   COMMENT ON COLUMN "ADMIN"."TIPBOARDCOMMENT"."NUM" IS '±Û¹øÈ£';
REM INSERTING into ADMIN.TIPBOARDCOMMENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TIPBOARDCOMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TIPBOARDCOMMENT_PK" ON "ADMIN"."TIPBOARDCOMMENT" ("RE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPBOARDCOMMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TIPBOARDCOMMENT" ADD CONSTRAINT "TIPBOARDCOMMENT_PK" PRIMARY KEY ("RE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TIPBOARDCOMMENT" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TIPBOARDCOMMENT" MODIFY ("RE_NUM" NOT NULL ENABLE);
